[package]
name = "TMCRO_Client"
version = "0.1.0"
authors = ["Rylux <ryckaert.guillaume@neuf.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json="^0.12"
log="^0.4"
